version: '3.8'
services:
  elevation-service:
    image: geometalab/elevation-service
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=on
    volumes:
      - ./backend:/retrieve-height-service
    ports:
      - "8080:5000"
