version: '3.3'
services:
  elevation-service:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/webapp:/retrieve-height-service/webapp
      - ./backend/app:/retrieve-height-service/app
      - ./data:/retrieve-height-service/data
    ports:
      - "8080:5000"